[project]
name = "manual-qa"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "动感chao人", email = "416608055@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "jieba>=0.42.1",
    "openai>=3.19.2",
    "pymupdf>=1.28.2",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.19.1",
    "rank-bm25>=0.2.2",
    "ruff>=0.16.8",
    "sse-starlette>=3.4.11",
    "uvicorn>=0.53.0",
]

[project.scripts]
manual-qa = "manual_qa:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
